FROM node:lts-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-*.yaml ./

RUN pnpm install --frozen-lockfile

COPY prisma ./prisma/

COPY . . 
RUN npm i -g dotenv-cli
RUN dotenv -e .env.local -- pnpm exec prisma generate

EXPOSE 3500

CMD ["pnpm", "dev"]
