FROM node:lts-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-*.yaml ./

RUN pnpm install --frozen-lockfile

COPY prisma ./prisma/

RUN pnpm exec prisma generate

COPY . . 

RUN pnpm store prune

RUN rm -rf /etc/apk/cache

EXPOSE 3500

CMD ["pnpm", "dev"]
